networks:
  app-network:
    driver: bridge

services:
  backend:
    image: hojiakbar2806/m-look_backend
    container_name: m-look-backend
    command: /bin/sh -c "alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 main:app"
    environment:
      - APP_ENV=production
      - DEBUG=False
      - RUN_ON_POSTGRES=True
    env_file:
      - m-look-back/.env  
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: hojiakbar2806/m-look_frontend
    container_name: m-look-frontend
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: m-look-postgres
    ports:
      - "5432:5432"
    env_file:
      - m-look-back/.env
    volumes:
      - ./postgres_container:/var/lib/postgresql/data
    networks:
      - app-network


  nginx:
    image: nginx:latest
    container_name: m-look-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "81:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network