"""User: update

Revision ID: 44065db4ac36
Revises: 029c4e4c670f
Create Date: 2024-11-13 11:34:03.542066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44065db4ac36'
down_revision: Union[str, None] = '029c4e4c670f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_prices_id', table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_table('products')
    op.drop_table('categories')
    op.drop_index('ix_profiles_id', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('ix_product_reviews_id', table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=250), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('hashed_password', sa.BLOB(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('product_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=255), nullable=False),
    sa.Column('average_rating', sa.FLOAT(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_reviews_id', 'product_reviews', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profiles_id', 'profiles', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('stock_in', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=255), nullable=False),
    sa.Column('selling_count', sa.INTEGER(), nullable=False),
    sa.Column('discount', sa.FLOAT(), nullable=False),
    sa.Column('for_whom', sa.VARCHAR(length=6), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('price_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['product_prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_prices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('current_amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('old_amount', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_prices_id', 'product_prices', ['id'], unique=False)
    # ### end Alembic commands ###
