name: M-Look deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build frontend Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_FRONTEND_IMAGE }}:latest
          no-cache: true

      - name: Build backend Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_BACKEND_IMAGE }}:latest
          no-cache: true

      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
          cd ~/m-look

          git pull origin main

          sudo rm -rf m-look-front m-look-back .github

          sudo docker pull hojiakbar2806/m-look_backend:latest

          sudo docker-compose down
          sudo docker-compose rm -f
          sudo docker-compose up -d

          sudo docker image prune -f
          sudo docker container prune -f
          EOF
